// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using steam.Data;

#nullable disable

namespace steam.Migrations
{
    [DbContext(typeof(SteamDBContext))]
    [Migration("20240127151642_seeddata")]
    partial class seeddata
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.1")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("steam.Models.Product", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Detail")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ImageUrl")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<float>("Price")
                        .HasColumnType("real");

                    b.Property<bool>("isTopPlayProduct")
                        .HasColumnType("bit");

                    b.Property<bool>("isTopSaleProduct")
                        .HasColumnType("bit");

                    b.Property<bool>("isTrendingProduct")
                        .HasColumnType("bit");

                    b.HasKey("Id");

                    b.ToTable("Product");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Detail = "Một tựa game Esport ",
                            ImageUrl = "https://www.facebook.com/384dc6ac-8ec5-4142-a956-765ef40eb0c0",
                            Name = "Counter Strike",
                            Price = 0f,
                            isTopPlayProduct = false,
                            isTopSaleProduct = false,
                            isTrendingProduct = false
                        },
                        new
                        {
                            Id = 2,
                            Detail = "Đến từ nhà làm game với kinh nghiệm 200 năm:))",
                            ImageUrl = "https://www.facebook.com/b3ed0f08-f5d7-406e-a84a-7f42f55156aa",
                            Name = "Leauge of Legend",
                            Price = 0f,
                            isTopPlayProduct = false,
                            isTopSaleProduct = false,
                            isTrendingProduct = false
                        },
                        new
                        {
                            Id = 3,
                            Detail = "Là con của LoL nhưng lúc nào cũng kêu bố nhái con",
                            ImageUrl = "https://www.facebook.com/384dc6ac-8ec5-4142-a956-765ef40eb0c0",
                            Name = "Arena of Valor",
                            Price = 0f,
                            isTopPlayProduct = false,
                            isTopSaleProduct = false,
                            isTrendingProduct = false
                        },
                        new
                        {
                            Id = 4,
                            Detail = "Sản phẩm bắn súng hay nhất mọi thời đại",
                            ImageUrl = "https://www.facebook.com/9a6ff2f0-2458-4ed5-aa19-16b07c0e6eb5",
                            Name = "Call of Duty: MW2",
                            Price = 1039000f,
                            isTopPlayProduct = false,
                            isTopSaleProduct = false,
                            isTrendingProduct = false
                        },
                        new
                        {
                            Id = 5,
                            Detail = "Nơi mà phản diện phải chạy trốn chính diện",
                            ImageUrl = "https://www.facebook.com/68ebb2aa-6122-49a7-a412-2c293302fd67",
                            Name = "DOOM",
                            Price = 750000f,
                            isTopPlayProduct = false,
                            isTopSaleProduct = false,
                            isTrendingProduct = false
                        },
                        new
                        {
                            Id = 6,
                            Detail = "Vị vua ngủ quên",
                            ImageUrl = "https://www.facebook.com/34eae0fd-4e55-4360-99a4-c077d48eb3f3",
                            Name = "PUBG: BATTLE GROUND",
                            Price = 0f,
                            isTopPlayProduct = false,
                            isTopSaleProduct = false,
                            isTrendingProduct = false
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
